services:
  app:
    image: message-hub:latest
    build:
      context: .
    container_name: messagehub
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - DATABASE_URL=mongodb://clearlens-mongodb:27017/messagehub
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://messagehub.viniduminsara.dev}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://messagehub.viniduminsara.dev}
    networks:
      - shared-db

networks:
  shared-db:
    external: true
