services:
  app:
    image: message-hub
    container_name: message-hub
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - DATABASE_URL=mongodb://clearlens-mongodb:27017/messagehub
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    networks:
      - shared-db

networks:
  shared-db:
    external: true
